version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: topicosAvanzados_db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TZ=America/La_Paz
      - PGTZ=America/La_Paz
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  app:
    image: nukesito/topicos-1:latest
    container_name: topicosAvanzados_app
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=development
      - JWT_SECRET=your_super_secret_jwt_key_here_make_it_long_and_secure
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
